/**
 * Autogenerated by Avro
 * 
 * DO NOT EDIT DIRECTLY
 */
package tmp.avro.stub;

@SuppressWarnings("all")
public interface SimpleService {
  public static final org.apache.avro.Protocol PROTOCOL = org.apache.avro.Protocol.parse("{\"protocol\":\"SimpleService\",\"namespace\":\"tmp.avro.stub\",\"types\":[{\"type\":\"record\",\"name\":\"Message\",\"fields\":[{\"name\":\"topic\",\"type\":\"string\",\"default\":null},{\"name\":\"content\",\"type\":\"bytes\",\"default\":null},{\"name\":\"createdTime\",\"type\":\"long\",\"default\":null},{\"name\":\"ids\",\"type\":\"string\",\"default\":null},{\"name\":\"ipAddress\",\"type\":\"string\",\"default\":null},{\"name\":\"props\",\"type\":{\"type\":\"map\",\"values\":\"string\"},\"default\":null}]}],\"messages\":{\"publish\":{\"request\":[{\"name\":\"context\",\"type\":\"string\",\"default\":null},{\"name\":\"messages\",\"type\":{\"type\":\"array\",\"items\":\"Message\"},\"default\":null}],\"response\":\"int\"}}}");
  int publish(java.lang.CharSequence context, java.util.List<tmp.avro.stub.Message> messages) throws org.apache.avro.AvroRemoteException;

  @SuppressWarnings("all")
  public interface Callback extends SimpleService {
    public static final org.apache.avro.Protocol PROTOCOL = tmp.avro.stub.SimpleService.PROTOCOL;
    void publish(java.lang.CharSequence context, java.util.List<tmp.avro.stub.Message> messages, org.apache.avro.ipc.Callback<java.lang.Integer> callback) throws java.io.IOException;
  }
}